#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
xrandr --output DisplayPort-0 --primary --off --output DisplayPort-1 --mode 1920x1080 --pos 0x790 --rotate normal --output DisplayPort-2 --off --output HDMI-A-0 --mode 2560x1080 --pos 1920x0 --rotate right
setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

pidof -sx "redshift -l -27.6:-48.5" &

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
